version: '3'
services:
  hoarder-service:
    image: dsek/hoarder-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - neo4j
    environment:
      NEO4J_HOST: neo4j
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      RUN_STARTUP_SCRIPTS: "true"
    build:
      context: .
    volumes:
      - "./database_init/:/startup-scripts/:ro"
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474"
      - "7473"
      - "7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - "./db/data/:/data/:rw"
      - "./db/logs/:/logs/:rw"
      - "./plugins/:/plugins/:ro"
      - "./db_import/:/var/lib/neo4j/import/:ro"
